### ISSUE TITLE
Rewrite existing example C++ project in Luna

### ISSUE THREAD

**Issue by Swordlash** [Luna-Tensorflow/Luna-Tensorflow#10] opened 2018-11-13 17:59 UTC
After writing our example project in C++, we should write similar one in Luna, creating similar wrappers for c_api functions using directly FFI. We should also think about how the Luna TF API would look like.

**Comment by radeusgd** [comment] 2018-12-06 21:02
#23 is a duplicate of this issue (sorry for that), but it has more discussion so let's move there and close this one.

**Closed as completed by radeusgd** 2018-12-06 21:02 UTC
Labels: duplicate
